<a href="https://colab.research.google.com/github/muneeb0065/Machine-Learning/blob/main/Naive_Bayes_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [12]:
data = pd.read_csv("play_tennis.csv")

In [13]:
data.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [14]:
# Drop the day coloums because there is no meaning of that coloumn
data.drop(columns=['day'] , inplace=True) # we use inplace = True so that it modify the existing data

In [17]:
# Now if we are given an problem that outlook= sunny, temp= hot, humidity= High, wind= weak
# and we have to predict whether there will be play on that day or not so by using naive bayes we can solve this as:
#
# P(Yes| sunny, hot , high, weak) will be written as : P(sunny|Yes) * P(hot|Yes) * P(High|Yes) * P(weak|Yes) * P(Yes)
# The denominator term is same in both case so we ignore it
# similarly
# P(No| sunny, hot , high , weak) and this can be written as: P(sunny|No) * P(hot|No) * P(High|No) * P(weak|No) * P(No)

In [18]:
# Now how naive solve this is by creating a lookup table where all the probabilities are stored and if any problem given it can solve by calculating
# Now we will create a lookup for naive bayes

In [21]:
# First we will calculate the probability of yes and no and it can be calculates as:

data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [23]:
P_Yes = 9/14
P_No = 5/14

print(P_Yes)
print(P_No)

0.6428571428571429
0.35714285714285715

In [24]:
# Now  we will calculate the probabilities of all the coloums
# 1st is Outlook coloumn

pd.crosstab(data['outlook'], data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [25]:
P_Overcast_Yes = 4/9
P_Rain_Yes = 3/9
P_Sunny_Yes = 2/9

P_Overcast_No = 0/5
P_Rain_No = 2/5
P_Sunny_No = 3/5

In [27]:
# Now 2nd coloum which is Temp

pd.crosstab(data['temp'], data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [35]:
P_Cool_Yes = 3/9
P_Hot_Yes = 2/9
P_Mild_Yes = 4/9

P_Cool_No = 1/5
P_Hot_No = 2/5
P_Mild_No = 2/5

In [29]:
# Now 3rd coloum which is Humidity

pd.crosstab(data['humidity'], data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [37]:
P_High_Yes = 3/9
P_Normal_Yes = 6/9

P_High_No = 4/5
P_Normal_No = 1/5

In [32]:
# Now 4th coloum which is Wind
pd.crosstab(data['wind'], data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [33]:
P_Strong_Yes = 3/9
P_Weak_Yes = 6/9

P_Srong_No = 3/5
P_Weak_No = 2/5

In [39]:
# Now we will solve our given problem
# outlook= sunny, temp= hot, humidity= High, wind= weak

Probability_of_Yes = P_Yes * P_Sunny_Yes * P_Hot_Yes * P_High_Yes * P_Weak_Yes
#Similarly
Probability_of_No = P_No * P_Sunny_No * P_Hot_No * P_High_No * P_Weak_No

# Now check both probability and which one is greater in our answer
print(Probability_of_Yes)
print(Probability_of_No)

0.007054673721340388
0.013714285714285715